/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmaciaprojeto;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author sala303b
 */
public class alterarMedicamento extends javax.swing.JFrame {

    /**
     * Creates new form alterarMedicamento
     */
    Carrinho c;
    int pos = 0;
    
    public alterarMedicamento() {
        initComponents();
    }
    public alterarMedicamento(Carrinho c){
        initComponents();
        this.c = c;
    }
    
    public void habilitarCampos(){
        tbCodigo.setEditable(true);
        tbLaboratorio.setEditable(true);
        tbQuantidade.setEditable(true);
        tbPreco.setEditable(true);
        btAlterarMedicamento.setEnabled(true);
    }
    public void desabilitarCampos(){
        tbCodigo.setEditable(false);
        tbLaboratorio.setEditable(false);
        tbQuantidade.setEditable(false);
        tbPreco.setEditable(false);
        btAlterarMedicamento.setEnabled(false);
    }
    
    public void limparCampos(){
        tbCodigo.setText("");
        tbNome.setText("");
        tbLaboratorio.setText("");
        tbQuantidade.setText("");
        tbPreco.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        tbLaboratorio = new javax.swing.JTextField();
        tbQuantidade = new javax.swing.JTextField();
        tbPreco = new javax.swing.JTextField();
        btAlterarMedicamento = new javax.swing.JButton();
        lbCodigo = new javax.swing.JLabel();
        lbLaboratorio = new javax.swing.JLabel();
        lbQuantidade = new javax.swing.JLabel();
        lbPreco = new javax.swing.JLabel();
        tbCodigo = new javax.swing.JTextField();
        btCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lbNome = new javax.swing.JLabel();
        tbNome = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbLaboratorio.setEditable(false);
        tbLaboratorio.setForeground(new java.awt.Color(255, 0, 0));

        tbQuantidade.setEditable(false);
        tbQuantidade.setForeground(new java.awt.Color(255, 0, 0));

        tbPreco.setEditable(false);
        tbPreco.setForeground(new java.awt.Color(255, 0, 0));

        btAlterarMedicamento.setBackground(new java.awt.Color(0, 240, 0));
        btAlterarMedicamento.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btAlterarMedicamento.setText("Alterar Medicamento");
        btAlterarMedicamento.setEnabled(false);
        btAlterarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarMedicamentoActionPerformed(evt);
            }
        });

        lbCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCodigo.setText("Codigo:");

        lbLaboratorio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbLaboratorio.setText("Laboratorio:");

        lbQuantidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbQuantidade.setText("Quantidade:");

        lbPreco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPreco.setText("Preço:");

        tbCodigo.setEditable(false);
        tbCodigo.setForeground(new java.awt.Color(255, 0, 0));

        btCancelar.setBackground(new java.awt.Color(240, 0, 0));
        btCancelar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Alterar Medicamento");

        lbNome.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbNome.setForeground(new java.awt.Color(255, 0, 0));
        lbNome.setText("Nome:");

        btPesquisar.setBackground(new java.awt.Color(0, 240, 0));
        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(lbNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btPesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbLaboratorio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbLaboratorio))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbCodigo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbQuantidade)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tbQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(29, 29, 29)
                                .addComponent(lbPreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btAlterarMedicamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(btCancelar)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(tbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo)
                    .addComponent(tbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLaboratorio)
                    .addComponent(tbLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuantidade)
                    .addComponent(tbQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPreco)
                    .addComponent(tbPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAlterarMedicamento)
                    .addComponent(btCancelar))
                .addGap(3, 3, 3)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAlterarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarMedicamentoActionPerformed

        Medicamento m = new Medicamento();
        m.setCodigo(Integer.parseInt(tbCodigo.getText()));
        m.setNome(tbNome.getText());
        m.setLaboratorio(tbLaboratorio.getText());
        m.setQuantidade(Integer.parseInt(tbQuantidade.getText()));
        m.setPreco(Double.parseDouble(tbPreco.getText()));
        c.med[pos] = m;
        JOptionPane.showMessageDialog(null, "Medicamento alterado");
        c.med[pos].exibirMedicamento();
        
        //desabilitando campos da tela Alterar
        desabilitarCampos();
        limparCampos();
    }//GEN-LAST:event_btAlterarMedicamentoActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        String nome = tbNome.getText();
        if (nome.equals("")) { //se o preenchimento for vazio faça.
            JOptionPane.showMessageDialog(null, "Digite um nome");
        } else {//se o preenchimento não for vazio.
            int i = c.pesquisarMedicamento(nome); //verificar se existe o medicamento.
            if (i < c.quant){//se(sim) achar o medicamento faça.
                //Passar os dados do medicamento para a tela
                Medicamento m = c.med[i];//medicamento no vetor.
                tbCodigo.setText(String.valueOf(m.getCodigo()));//colocar o codigo na tela.
                tbLaboratorio.setText(m.getLaboratorio());//colocar o laboratorio na tela.
                tbQuantidade.setText(String.valueOf(m.getQuantidade()));//colocar a quantidade na tela.
                DecimalFormat df = new DecimalFormat("#,00");//usar o decimalformat para o preço.
                tbPreco.setText(df.format(m.getPreco()));//colocar preco na tela.                
                //habilitar campos da tela
                habilitarCampos();              
                pos = i;              
            } else {
                JOptionPane.showMessageDialog(null, "Medicamento não registrado");
            } 
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alterarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alterarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alterarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alterarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alterarMedicamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarMedicamento;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbLaboratorio;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbPreco;
    private javax.swing.JLabel lbQuantidade;
    private javax.swing.JTextField tbCodigo;
    private javax.swing.JTextField tbLaboratorio;
    private javax.swing.JTextField tbNome;
    private javax.swing.JTextField tbPreco;
    private javax.swing.JTextField tbQuantidade;
    // End of variables declaration//GEN-END:variables
}
