/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmaciaprojeto;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author sala303b
 */
public class TelaUnica extends javax.swing.JFrame {

    /**
     * Creates new form TelaUnica
     */
    Carrinho c;
    int pos = 0;
    String clicou = "";

    public TelaUnica() {
        initComponents();
        c = new Carrinho();

        Medicamento m1 = new Medicamento(111, "Dipirona", "EMS", 12, 14.90);
        Medicamento m2 = new Medicamento(222, "Paracetamol", "Neoquimaca", 18, 5.91);
        Medicamento m3 = new Medicamento(333, "Ibuprofeno", "Ache", 20, 20.96);
        c.inserirMedicamento(m1);
        c.inserirMedicamento(m2);
        c.inserirMedicamento(m3);
    }

    public void habilitarCampos() {
        tbCodigo.setEditable(true);
        tbLaboratorio.setEditable(true);
        tbQuantidade.setEditable(true);
        tbPreco.setEditable(true);
        btSalvar.setEnabled(true);
    }

    public void desabilitarCampos() {
        tbCodigo.setEditable(false);
        tbLaboratorio.setEditable(false);
        tbQuantidade.setEditable(false);
        tbPreco.setEditable(false);
        btSalvar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btInserir = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tbNome = new javax.swing.JTextField();
        tbCodigo = new javax.swing.JTextField();
        tbPreco = new javax.swing.JTextField();
        tbLaboratorio = new javax.swing.JTextField();
        tbQuantidade = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btInserirM = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Menu Principal");

        btInserir.setText("Inserir novo Medicamento");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        btPesquisar.setText("Pesquisar Medicamento");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar Medicamento");
        btAlterar.setEnabled(false);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir Medicamento");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel3.setText("Codigo:");

        jLabel4.setText("Laboratorio:");

        jLabel5.setText("Quantidade:");

        jLabel6.setText("Preço:");

        tbCodigo.setEditable(false);

        tbPreco.setEditable(false);

        tbLaboratorio.setEditable(false);

        tbQuantidade.setEditable(false);

        btSalvar.setText("Salvar alteração");
        btSalvar.setEnabled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btInserirM.setText("Inserir");
        btInserirM.setEnabled(false);
        btInserirM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirMActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.setEnabled(false);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(259, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(235, 235, 235))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btInserirM)
                        .addGap(18, 18, 18)
                        .addComponent(btCancelar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(119, 119, 119)
                                    .addComponent(jLabel3))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(93, 93, 93)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tbLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(tbCodigo)
                                .addComponent(tbQuantidade)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(126, 126, 126)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tbPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btInserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(tbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(tbLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(tbQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(tbPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btSalvar)
                                .addComponent(btInserirM)
                                .addComponent(btCancelar)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPesquisar))
                        .addGap(78, 78, 78)
                        .addComponent(btInserir)
                        .addGap(18, 18, 18)
                        .addComponent(btAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(btExcluir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed

        limparCampos();
        habilitarCampos();
        btInserir.setEnabled(false);
        btInserirM.setEnabled(true);
        btCancelar.setEnabled(true);
        btSalvar.setEnabled(false);
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
        
        clicou = "inserir";
    }//GEN-LAST:event_btInserirActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        desabilitarCampos();
        btInserirM.setEnabled(false);
        btInserir.setEnabled(true);
        String nome = tbNome.getText();

        if (nome.equals("")) { //se o preenchimento for vazio faça.
            JOptionPane.showMessageDialog(null, "Digite um nome");
        } else {//se o preenchimento não for vazio.
            int i = c.pesquisarMedicamento(nome); //verificar se existe o medicamento.
            if (i < c.quant) {//se(sim) achar o medicamento faça.
                //Passar os dados do medicamento para a tela
                Medicamento m = c.med[i];//medicamento no vetor.
                tbCodigo.setText(String.valueOf(m.getCodigo()));//colocar o codigo na tela.
                tbLaboratorio.setText(m.getLaboratorio());//colocar o laboratorio na tela.
                tbQuantidade.setText(String.valueOf(m.getQuantidade()));//colocar a quantidade na tela.
                DecimalFormat df = new DecimalFormat("#,00");//usar o decimalformat para o preço.
                tbPreco.setText(df.format(m.getPreco()));//colocar preco na tela.
                btAlterar.setEnabled(true);
                btExcluir.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "Medicamento não registrado");
                limparCampos();
            }
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        Medicamento m = new Medicamento();
        m.setCodigo(Integer.parseInt(tbCodigo.getText()));
        m.setNome(tbNome.getText());
        m.setLaboratorio(tbLaboratorio.getText());
        m.setQuantidade(Integer.parseInt(tbQuantidade.getText()));
        m.setPreco(Double.parseDouble(tbPreco.getText()));
        c.med[pos] = m;
        JOptionPane.showMessageDialog(null, "Medicamento alterado");
        c.med[pos].exibirMedicamento();

        //desabilitando campos da tela Alterar
        desabilitarCampos();
        limparCampos();
        btAlterar.setEnabled(false);
        btCancelar.setEnabled(false);
        btInserir.setEnabled(true);
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        //btInserir.setEnabled(false);
        btExcluir.setEnabled(false);
        btCancelar.setEnabled(true);
        btAlterar.setEnabled(false);
        btInserir.setEnabled(false);
        String nome = tbNome.getText();
        if (nome.equals("")) { //se o preenchimento for vazio faça.
            JOptionPane.showMessageDialog(null, "Digite um nome");
        } else {
            habilitarCampos();
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btInserirMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirMActionPerformed

        String nome = tbNome.getText();

        if (nome.equals("")) {
            JOptionPane.showMessageDialog(null, "Digite um nome");
        } else {
            int i = c.pesquisarMedicamento(nome);
            if (i < c.quant) {
                JOptionPane.showMessageDialog(null, "Medicamento já cadastrado");
                limparCampos();
                desabilitarCampos();
                btInserirM.setEnabled(false);
            } else {
                Medicamento m = new Medicamento();

                m.setCodigo(Integer.parseInt(tbCodigo.getText()));//colocar o codigo dentro de tbCodigo.
                m.setNome(tbNome.getText());//colocar o nome dentro de tbNome.
                m.setLaboratorio(tbLaboratorio.getText());//colocar o laboratorio dentro de tbLaboratorio.
                m.setQuantidade(Integer.parseInt(tbQuantidade.getText()));//colocar quantidade dentro de lbQuantidade.
                m.setPreco(Double.parseDouble(tbPreco.getText()));//colocar preco dentro de tbPreco.

                if (c.quant < 10) { //verificar se o meu carrinho é menor que 10.
                    c.med[c.quant] = m; //se não tiver lotado...
                    c.quant++; //ele insere o meu medicamento no carrinho.

                    JOptionPane.showMessageDialog(null, "Medicamento inserido");
                } else {
                    JOptionPane.showMessageDialog(null, "Carrinho Lotado");
                }
                //Exibindo informações do carrinho
                for (i = 0; i < c.quant; i++) {
                    m = c.med[i];
                    m.exibirMedicamento();
                }
            }
            limparCampos();
            desabilitarCampos();
            btInserirM.setEnabled(false);
            btCancelar.setEnabled(false);
            btInserir.setEnabled(true);
        }
    }//GEN-LAST:event_btInserirMActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        String nome = tbNome.getText();

        if (nome.equals("")) { //se o preenchimento for vazio faça.
            JOptionPane.showMessageDialog(null, "Digite um nome");
        } else {//se o preenchimento não for vazio.
            int i = c.pesquisarMedicamento(nome); //verificar se existe o medicamento.
            if (i < c.quant) {//se(sim) achar o medicamento faça.
                String r = JOptionPane.showInputDialog(null, "Confirma exclusão [S|N]?");
                if (r.equals("S")) {
                    //Copiar o ultimo medicamento para a posição i
                    c.quant--; //diminuir
                    c.med[i] = c.med[c.quant]; //substituir o ultimo para a posição i
                    JOptionPane.showMessageDialog(null, "Medicamento Excluido");
                    for (i = 0; i < c.quant; i++) {
                        c.med[i].exibirMedicamento();
                        limparCampos();
                        btAlterar.setEnabled(false);
                        btExcluir.setEnabled(false);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Medicamento não Excluido");
                    limparCampos();
                    btAlterar.setEnabled(false);
                    btExcluir.setEnabled(false);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Medicamento não registrado");
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        limparCampos();
        desabilitarCampos();
        //btInserir.setEnabled(false);
        btExcluir.setEnabled(false);
        btInserirM.setEnabled(false);
        btCancelar.setEnabled(false);
        btAlterar.setEnabled(false);
        btInserir.setEnabled(true);

    }//GEN-LAST:event_btCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUnica().setVisible(true);
            }
        });
    }

    public void limparCampos() {
        tbCodigo.setText("");
        tbNome.setText("");
        tbLaboratorio.setText("");
        tbQuantidade.setText("");
        tbPreco.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btInserirM;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField tbCodigo;
    private javax.swing.JTextField tbLaboratorio;
    private javax.swing.JTextField tbNome;
    private javax.swing.JTextField tbPreco;
    private javax.swing.JTextField tbQuantidade;
    // End of variables declaration//GEN-END:variables
}
