/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmaciaprojeto;

/**
 *
 * @author sala303b
 */
public class TelaInicial extends javax.swing.JFrame {
    
    Carrinho c; //Atribudo da classe

    public TelaInicial() {
        initComponents();
        c = new Carrinho(); //iniciando carrinho

        //Adicionando medicamentos no carrinho para teste
        Medicamento m1 = new Medicamento(111, "Dipirona", "EMS", 12, 14.90);
        Medicamento m2 = new Medicamento(222, "Paracetamol", "Neoquimaca", 18, 5.91);
        Medicamento m3 = new Medicamento(333, "Ibuprofeno", "Ache", 20, 20.96);
        c.inserirMedicamento(m1);
        c.inserirMedicamento(m2);
        c.inserirMedicamento(m3);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        menuMedicamentos = new javax.swing.JMenu();
        menuInserir = new javax.swing.JMenuItem();
        menuAlterar = new javax.swing.JMenuItem();
        menuExcluir = new javax.swing.JMenuItem();
        menuPesquisar = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        menuEncerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuMedicamentos.setText("Medicamento");
        menuMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMedicamentosActionPerformed(evt);
            }
        });

        menuInserir.setText("Inserir");
        menuInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInserirActionPerformed(evt);
            }
        });
        menuMedicamentos.add(menuInserir);

        menuAlterar.setText("Alterar");
        menuAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlterarActionPerformed(evt);
            }
        });
        menuMedicamentos.add(menuAlterar);

        menuExcluir.setText("Excluir");
        menuExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExcluirActionPerformed(evt);
            }
        });
        menuMedicamentos.add(menuExcluir);

        menuPesquisar.setText("Pesquisar");
        menuPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPesquisarActionPerformed(evt);
            }
        });
        menuMedicamentos.add(menuPesquisar);

        barraMenu.add(menuMedicamentos);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });

        menuEncerrar.setText("Encerrar");
        menuEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEncerrarActionPerformed(evt);
            }
        });
        menuSair.add(menuEncerrar);

        barraMenu.add(menuSair);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPesquisarActionPerformed
        
        pesquisarMedicamento fPesq = new pesquisarMedicamento(c);//pegar o JFrame do pesquisarMedicamento e colocar na tenaInicial
        fPesq.setVisible(true);//deixar vizivel o menu pesquisarMedicamento
    }//GEN-LAST:event_menuPesquisarActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed

    }//GEN-LAST:event_menuSairActionPerformed

    private void menuEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEncerrarActionPerformed
        System.exit(0);//fechar aplicação.
    }//GEN-LAST:event_menuEncerrarActionPerformed

    private void menuInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInserirActionPerformed
        inserirMedicamento pMed = new inserirMedicamento(c);
        pMed.setVisible(true);
    }//GEN-LAST:event_menuInserirActionPerformed

    private void menuAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlterarActionPerformed
        alterarMedicamento aMed = new alterarMedicamento(c);//pegar o JFrame do alterarMedicamento e colocar na tenaInicial
        aMed.setVisible(true);//deixar vizivel.
    }//GEN-LAST:event_menuAlterarActionPerformed

    private void menuExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExcluirActionPerformed
        excluirMedicamento eMed = new excluirMedicamento(c);
        eMed.setVisible(true);
    }//GEN-LAST:event_menuExcluirActionPerformed

    private void menuMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMedicamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMedicamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem menuAlterar;
    private javax.swing.JMenuItem menuEncerrar;
    private javax.swing.JMenuItem menuExcluir;
    private javax.swing.JMenuItem menuInserir;
    private javax.swing.JMenu menuMedicamentos;
    private javax.swing.JMenuItem menuPesquisar;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
